language: node_js
node_js:
- '8'
install:
- cd todo/
- npm install
script:
- npm run lint
- npm test
before_deploy:
- npm run build
- zip -r build.zip build/*
- git config --local user.name "Nate Rauh"
- git config --local user.email "NRauh@users.noreply.github.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: 0srKDToTDNPKR+H4Sc2sdrfj10JpuEG/iRof31S20Cp1SgqicfoentkUUG5de+4RDtV+eXG/mTo+eogXtl57p8w9Y1avDbfxXMNir+yNIMKGtRxTbs8DTi2+TWrpQsK6uABmyy87cB8NuQWVeuQYjHwU3iGtrP9A4YOfBttXQohLeAB6ZVVQ7MMRsUUf8F4v1G6I/X8yoVu+UT/8xg/fx89fhG/FPd1dB+jF79cS9mDPBAf8FDOwoyuuCgJdNYdVnjBqE15Ew5nCMrtodUH8byP3T1qnQd26ZKxQGczjvVOwFbg/zpTCyaYVk7o4Pm/tMZSfDNDyZoKFzXNdYKpN+YjIpClip2oOroFUTWN7w8zN+8XpFM4ZK+jjlaabZINLIqvyKK9/nRJGcG4y2b60sKzoXLNLWBQmGvVcEUE2VhSxPk92EX5noFBRIFMFWWQfmQZc4upbFWiGTxtx4VwcIlxvmcNrNMTgdWfYhk95DJTaUhythJimSDdwVIzgi8ksYm2JBuvgOnQFLsipe45E/XC0g9rBVC60IxpMhXxhYOpnZiQWFZPLysIw9uGd07MJbcXan0uZzFSWXIIqOxYsfWqNY67xXUIQ1WvSIPqzoG52A09qq22WAJ4pgn2lBwY350tirA2+ViXYjow7E/ETG/RVZ5FDSI0erpGt+AcR0L8=
  file: build.zip
  skip_cleanup: true
  on:
    repo: NRauh/devops-talk
    branch: master
